# COMM 187: Data Science in Communication Research
# Spring 2025

## Week #2 Coding Lab: Python Fundamentals
**Monday, April 7, 2025**

Welcome to the first Coding Lab for **COMM 187: Data Science in Communication Research!**

Today's lesson plan:
 - Python Basics Review: Lists, Functions, Packages, and NumPy

## What is Jupyterhub?

To write and execute Python code, you need a platform or software which helps you do that. **Jupyter** is one such interactive platform for Python programming. Jupyter's name is a reference to the three core programming languages supported by Jupyter, which are **Ju**lia, **Pyt**hon and **R**! On Jupyter, you can write code and execute its output right underneath it. More importantly, Jupyter can be hosted on a server, which means that the code runs on the server and not your computer. This is helpful for us, because we do not need to install anything on our computers, and we can simply write and execute Python code using Jupyter.

What you are currently viewing this on is the Jupyter**Lab** environment. Here, you can have multiple tabs open, with different types of coding environments, along with a side bar (on the left side of the screen) which displays a file system. 

### Jupyter Notebooks

The Jupyter Notebook is at the heart of what Jupyter offers as a platform -- it is an interactive document for code, text, data visualizations, and other output. This document you are reading right now is a notebook too! 

Jupyter Notebooks are organized into cells. You might have noticed that the text in this notebook thus far has been organized into "chunks", which are indicated by a blue ribbon on the left margin. These "chunks" are called cells, and can be of three types:

1. **Raw:** This is raw, unformatted text.
2. **Markdown:** This is a piece of text formatted using Markdown, which is a markup language used to add formatting to text. HTML is another markup language!
4. **Code:** As the name says, this is a piece of code which can be executed!

Look at the top ribbon, you might see the following icons:

![ribbon](./imgs/JupyterlabRibbon.png)

You can use the `+` sign to add a new cell to this notebook.

Now, if you click on "Markdown", you will see three options emerge: Code, Markdown, and Raw.

![CellOptions](./imgs/JupyterlabCellOptions.png)

Try out these different cell types, and see what it looks like to type in cells of different types. \
Do the colors and formatting of the texts change in different cell types?

### Let us write some code!

Follow these steps: 

1. Use the `+` button in the top ribbon to make a new cell below
2. Write the following in it: `1+1`
3. Execute the cell (either use the play button on the top ribbon or the shortcut!)

In [1]:
1+1

2

**TIP:** You can execute a cell by using the following shortcut: Ctrl + Enter (on Windows), Command + Enter (on Mac)

## Python Basics Review Exercise

### Question 1

 - Create a new **int**, `var_int`, with the value 12.
 - Create a new **float**, `var_float`, with the value 0.5.
 - Create a new **string**, `var_string`, with the value "Week 2!".
 - Create a new **boolean**, `var_bool`, with the value `False`.


In [2]:
### Write your code below this line by replacing ...
var_int = 12
var_float = 0.5
var_string = "Week 2!"
var_bool = False

### Question 2

 - Create a variable `insta_views` with the value of 250.
 - Check out this variable by typing `print(insta_views)`.

In [3]:
### Write your code below this line by replacing ...
insta_views = 250
print(insta_views)

250


### Question 3

 - Create a variable `views_per_minute`, equal to 7 and `num_minutes`, equal to 360.
 - Multiply `views_per_minute` by `num_minutes` and assign it to `new_insta_views`.
 - Print the value of `new_insta_views`.

In [5]:
### Write your code below this line by replacing ...
views_per_minute = 7
num_minutes = 360
new_insta_views = views_per_minute*num_minutes
print(new_insta_views)

2520


### Question 4

 - Create a variable `views_per_minute`, equal to 7 and `num_minutes`, equal to 360.
 - Multiply `views_per_minute` by `num_minutes` and assign it to `new_insta_views`.
 - Print the value of `new_insta_views`.

In [5]:
### Write your code below this line by replacing ...
views_per_minute = 7
num_minutes = 360
new_insta_views = views_per_minute*num_minutes
print(new_insta_views)

2520


### Question 5

 - Create a list, `social_media`, that contains the number of minutes spent on Instagram (`insta`), Snapchat (`snap`), Tiktok (`tiktok`), Facebook (`facebook`) and X (`x`), in this order. Use the predefined variables.
 - Print areas with the `print()` function.


In [6]:
insta = 240
snap = 120
tiktok = 30
facebook = 5
x = 150
### Write your code below this line by replacing ...
social_media = [insta, snap, tiktok, facebook, x]
print(social_media)

[240, 120, 30, 5, 150]


### Question 6

 - Use `print()` in combination with type() to print out the type of `social_media`.
 - Use `len()` to get the length of the list `social_media`. 
 - Use `int()` to convert `fb_active` to an integer. Store the output as `fb_active2`.
 - Use `float()` to convert `fb_minutes` to a float. Store the output as `fb_minutes2`.


In [7]:
fb_active = True
fb_minutes = "120.5"
### Write your code below this line by replacing ...
print(type(social_media))

<class 'list'>


In [8]:
len(social_media)

5

In [10]:
fb_active2 = int(fb_active)

In [11]:
fb_minutes2 = float(fb_minutes)
print(fb_minutes2)

120.5


### Question 7

 - Use `sorted()` function to sort `social_media` in descending order, i.e., highest value first, and store it in a new variable `social_media_sorted`.
 - Use `help()` or `?` to figure out the **documentation** of `sorted()` function

In [13]:
### Write your code below this line by replacing ...
social_media_sorted = sorted(social_media, reverse=True)
print(social_media_sorted)

[240, 150, 120, 30, 5]


In [14]:
?sorted

Signature: sorted(iterable, /, *, key=None, reverse=False)
Docstring:
Return a new list containing all items from the iterable in ascending order.

A custom key function can be supplied to customize the sort order, and the
reverse flag can be set to request the result in descending order.
Type:      builtin_function_or_method

### Question 8

The list `fb_usage_2024` contains the number of minutes spent on Facebook by a user per day in the year 2024, starting from January 1, ending in December 31.

 - Use `.index()` method to find the index of the first element in the list `fb_usage_2024` that is equal to **200** 
 - Use `.count()` method to count the number of times the value **135** appears in the list `fb_usage_2024`
 - Use `help()` or `?` to figure out the **documentation** of `.index()` method by typing `?fb_usage_2024.index`. Same for `.count()` method.

In [1]:
fb_usage_2024 = [100,  80, 100,  95,  95,  95, 135,  10,  55,  90,  50, 195,  75,
                          120,  50,  75, 230,   5, 235, 240, 105,  60, 175,  65, 210,  60,
                          115,  15, 195,  90, 130,  25,  35, 140,   0, 210,   0, 125, 195,
                          80,  45,  60, 205,   0,  80, 150,  45, 210, 200, 140, 155, 235,
                          165,  30, 220, 165,   0,  95,  70,   0,  80, 235,  25,  45, 170,
                          25,  75, 170, 100, 145, 195, 150, 225, 165,  40, 180,  55,  25,
                          170, 200, 240, 110, 245,  70,  30,  25, 100, 225,  70,  20, 150,
                          135,  50,  95,  15,  35, 205,  85, 235, 100,  70, 185, 220, 225,
                          35, 130, 125,  25,  20, 125, 205, 125, 125, 110, 180, 245, 190,
                          200, 170, 125, 185,  90, 190, 240,  15,  40,  65, 165,   0,  45,
                          180, 105, 180, 240,  70,  65,  45, 220,  90,  25, 230,  75,  35,
                          90, 225, 225, 190, 110, 120, 100, 120, 220, 180, 215, 245, 240,
                          25, 155,  95, 100, 175,  80, 170,  80, 215, 190, 135,  20,  60,
                          60,  90, 180, 145, 155, 185, 125,  80,  65,   5, 155, 105, 230,
                          10, 170,  85,  55, 215,  25, 170,  15, 120, 170, 145, 135,  10,
                          225, 150,  55, 215, 100, 145,  85, 155,  65, 170, 105,  95, 115,
                          90,  80, 170, 160, 125, 210, 145,   0, 165,  35,  45,  90, 145,
                          55, 165,  95, 235,  15,   0, 225,  95,  90,  95, 150, 155, 125,
                          85, 185, 195, 170, 190,   0, 190, 200, 105,  85, 210,  70, 100,
                          220,  55, 210,  70, 165, 185, 220, 150, 230, 155,   0,  15, 205,
                          110, 175, 240,  80,  65, 245,  70,  10,  95,  65, 190,  45,  55,
                          145, 110,  15,  30, 155,  40, 155, 150, 150,  75,  40, 190, 180,
                          65, 135,   5, 160,  75, 215, 210,  25,  20, 130, 115,  40, 105,
                          215, 215,  40, 115, 200, 165,  35, 185, 235, 125,  50, 175,  45,
                          155, 200,  40, 100, 125,  55,  35, 115, 135, 135,  70, 100, 240, 
                          40, 240, 125,   0, 235,   0,  95,  30,  65, 105, 130,  85,   0, 
                          0, 135, 205,  25,  75, 165,  80,  25, 115, 145,   5,  10,  80,
                          235, 135, 240, 125, 240, 110, 245,  80, 220, 230, 155, 155, 200, 165,  65]

### Write your code below this line by replacing ...
print(fb_usage_2024.index(200))
print(fb_usage_2024.count(135))

48
9


In [5]:
?fb_usage_2024.index

Signature: fb_usage_2024.index(value, start=0, stop=9223372036854775807, /)
Docstring:
Return first index of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method

### Question 9

 - Import `numpy` as `np`
 - Import the mathematical constant `e` from package `math`
 - Import the `pyplot` subpackage of the `matplotlib` package as `plt`

In [6]:
### Write your code below this line by replacing ...
import numpy as np
from math import e
from matplotlib import pyplot as plt

### Question 10

Consider the following two lists, `list1` and `list2`.

 - Make a new list `list_plus` by using the `+` operator between `list1` and `list2`
 - Convert `list1` to numpy array `np1`, and `list2` to numpy array `np2`
 - Make a new numpy array `np_plus` by using the `+` operator between `np1` and `np2`
 - Convert `list_plus` to numpy array `np3`, and run the following expression: `np3 + np_plus`

In [14]:
list1 = [40.0, 23, True, 1]
list2 = [False, 12.3, 1, 20]
### Write your code below this line by replacing ...
list_plus = list1 + list2
print(list_plus)

[40.0, 23, True, 1, False, 12.3, 1, 20]


In [15]:
np1 = np.array(list1)
np2 = np.array(list2)
print(np1)
print(np2)

[40. 23.  1.  1.]
[ 0.  12.3  1.  20. ]


In [16]:
np_plus = np1 + np2
print(np_plus)

[40.  35.3  2.  21. ]


In [17]:
np3 = np.array(list_plus)
print(np3)

[40.  23.   1.   1.   0.  12.3  1.  20. ]


In [13]:
np3 + np_plus

ValueError: operands could not be broadcast together with shapes (8,) (4,) 

<span style="color:red">**INSTRUCTOR NOTE:** You receive an error here because you cannot add numpy arrays of different sizes.</span>

### Question 11

 - Convert `fb_usage_2024` to a numpy array called `fb_usage_2024_np`
 - Print the type of `fb_usage_2024_np` to ensure that it is a numpy array

In [19]:
### Write your code below this line by replacing ...
fb_usage_2024_np = np.array(fb_usage_2024)
print(type(fb_usage_2024_np))

<class 'numpy.ndarray'>


### Question 12

 - Print out a sub-array of `fb_usage_2024_np` that contains the elements at index 21 up to and including index 194.
 - The first element in `fb_usage_2024_np` corresponds to Facebook usage on Jan 1, 2024, the second element corresponds to Jan 2, so on and so forth. Make a new numpy array `fb_march_to_june` with the sub-array of `fb_usage_2024_np` that contains the Facebook usage from dates **March 1, 2024** to **June 30, 2024.** 

In [21]:
### Write your code below this line by replacing ...
print(fb_usage_2024_np[21:195])

[ 60 175  65 210  60 115  15 195  90 130  25  35 140   0 210   0 125 195
  80  45  60 205   0  80 150  45 210 200 140 155 235 165  30 220 165   0
  95  70   0  80 235  25  45 170  25  75 170 100 145 195 150 225 165  40
 180  55  25 170 200 240 110 245  70  30  25 100 225  70  20 150 135  50
  95  15  35 205  85 235 100  70 185 220 225  35 130 125  25  20 125 205
 125 125 110 180 245 190 200 170 125 185  90 190 240  15  40  65 165   0
  45 180 105 180 240  70  65  45 220  90  25 230  75  35  90 225 225 190
 110 120 100 120 220 180 215 245 240  25 155  95 100 175  80 170  80 215
 190 135  20  60  60  90 180 145 155 185 125  80  65   5 155 105 230  10
 170  85  55 215  25 170  15 120 170 145 135  10]


For the second part of this question, let's figure out the position in the list for the first day in March:

January (31 days) + February (29 days, leap year) + March (1 day)

The **index** will be one less than the position. Remember, the first position in the list is at index 0, the second position is at index 1, so on and so forth.

In [22]:
march_1_position = 31 + 29 + 1
march_1_index = march_1_position - 1

Now, let's figure out the position, and then index, in the list for the last day in June:

January (31 days) + February (29 days, leap year) + March (31 days) + April (30 days) + May (31 days) + June (30 days)

In [23]:
june_30_position = 31 + 29 + 31 + 30 + 31 + 30
june_30_index = june_30_position - 1

Now, let's use these indices to slice the list and create `fb_march_to_june`. 

Note that we are using `june_30_index+1` as the stop index, because we want to include the data for the 30th day of June.

In [27]:
fb_march_to_june = fb_usage_2024_np[march_1_index:june_30_index+1]
print(fb_march_to_june)

[ 80 235  25  45 170  25  75 170 100 145 195 150 225 165  40 180  55  25
 170 200 240 110 245  70  30  25 100 225  70  20 150 135  50  95  15  35
 205  85 235 100  70 185 220 225  35 130 125  25  20 125 205 125 125 110
 180 245 190 200 170 125 185  90 190 240  15  40  65 165   0  45 180 105
 180 240  70  65  45 220  90  25 230  75  35  90 225 225 190 110 120 100
 120 220 180 215 245 240  25 155  95 100 175  80 170  80 215 190 135  20
  60  60  90 180 145 155 185 125  80  65   5 155 105 230]


### Question 13

You are tracking the number of news alerts you receive on your phone everyday in the morning, afternoon, evening, and night. Here is what you gathered from last week, where for each day you have the number of news alerts received in the `[morning, afternoon, evening, and night]`:

 - Monday: `[7, 0, 5, 2]`
 - Tuesday: `[5, 1, 0, 1]`
 - Wednesday: `[2, 0, 4, 2]`
 - Thursday: `[4, 1, 3, 1]`
 - Friday: `[6, 1, 3, 1]`

Make a 2D numpy array called `news_alerts` in which each row has data from each day, in sequence. 

In [43]:
### Write your code below this line by replacing ...
news_alerts = np.array([[7, 0, 5, 2],
                       [5, 1, 0, 1],
                       [2, 0, 4, 2],
                       [4, 1, 3, 1],
                       [6, 1, 3, 1]])

In [30]:
print(news_alerts)

[[7 0 5 2]
 [5 1 0 1]
 [2 0 4 2]
 [4 1 3 1]
 [6 1 3 1]]


### Question 14

Write the code that will subset `news_alerts` to print the following array:

```
array([[1, 0, 1],
       [0, 4, 2],
       [1, 3, 1]])
```

In [34]:
### Write your code below this line by replacing ...
news_alerts[1:4, 1:4]

array([[1, 0, 1],
       [0, 4, 2],
       [1, 3, 1]])

### Question 15

 - Create a new variable `evenings` by indexing the third column of `news_alerts`
 - Print out the mean of `evenings`
 - Print out the median of `evenings`

In [38]:
### Write your code below this line by replacing ...
evenings = news_alerts[:,2]
print(evenings)

[5 0 4 3 3]


In [39]:
np.mean(evenings)

np.float64(3.0)

In [40]:
np.median(evenings)

np.float64(3.0)

### Question 16

You have been notified that you have incorrectly measuring your afternoon news alerts. To correct your data, you need to make the following changes to your data

 - Monday: Add 2 more news alerts
 - Tuesday: Add 3 more news alerts
 - Wednesday: Add 1 more news alert
 - Thursday: stays the same
 - Friday: Add 5 more news alerts

Make a new numpy array `update` which has the values outlined above in sequence. Then, add it to the second column of `news_alerts` and print it.

In [44]:
### Write your code below this line by replacing ...
update = [2, 3, 1, 0, 5]
news_alerts[:,1] = news_alerts[:,1] + update

In [45]:
print(news_alerts)

[[7 2 5 2]
 [5 4 0 1]
 [2 1 4 2]
 [4 1 3 1]
 [6 6 3 1]]
